namespace LibSsh2CS.UnitTests.PemKey;

/// <summary>
/// PemKey.Parse tests — verifies the type-specific private key blob parsing for
/// RSA, Ed25519 (and ECDSA when fixtures are available). Uses the same Phase 0
/// fixtures as PemParserTests (ssh-keygen-generated keys, plain + encrypted).
/// </summary>
public class PemKeyParseTests
{
    /// <summary>
    /// Parses an unencrypted Ed25519 key via PemParser then PemKey.Parse; asserts
    /// the seed is 32 bytes, the public key is 32 bytes, and the keytype is
    /// Ed25519.
    /// </summary>
    [Fact]
    public void Parse_Ed25519Plain_ExtractsSeedAndPublicKey()
    {
        byte[] keyBytes = FixtureLoader.LoadBytes("ed25519_plain_key");
        OpenSshKey openSshKey = SshPemParser.ParseOpenSshPrivateKey(keyBytes, passphrase: null);
        var pemKey = SshPemKey.Parse(openSshKey);

        Assert.Equal(SshKeyType.Ed25519, pemKey.KeyType);
        var ed = (SshEd25519PemKey)pemKey;
        Assert.Equal(32, ed.Seed.Length);
        Assert.Equal(32, ed.PublicKey.Length);

        // The public key blob from the .pub file should contain the same 32-byte
        // public key. The .pub blob is [string "ssh-ed25519"][string 32-byte A];
        // the 32-byte A is at offset 4+11+4 = 19.
        string pubFile = FixtureLoader.LoadText("ed25519_plain_key.pub");
        byte[] pubBlob = FixtureLoader.ParsePubFileBlob(pubFile);
        byte[] pubFromFile = new byte[32];
        Buffer.BlockCopy(pubBlob, 4 + 11 + 4, pubFromFile, 0, 32);
        Assert.Equal(pubFromFile, ed.PublicKey);
    }

    /// <summary>
    /// Parses a passphrase-encrypted Ed25519 key with the correct passphrase;
    /// asserts the seed and public key are the right lengths and the keytype
    /// is Ed25519. (The encrypted and plain fixtures are distinct keys —
    /// generated by separate ssh-keygen runs — so they don't share a public
    /// key; this test only checks the parse produces a well-formed Ed25519 key.)
    /// </summary>
    [Fact]
    public void Parse_Ed25519EncryptedCorrectPassphrase_ExtractsValidKey()
    {
        byte[] keyBytes = FixtureLoader.LoadBytes("ed25519_enc_key");
        OpenSshKey openSshKey = SshPemParser.ParseOpenSshPrivateKey(keyBytes, passphrase: "test123");
        var pemKey = SshPemKey.Parse(openSshKey);

        Assert.Equal(SshKeyType.Ed25519, pemKey.KeyType);
        var ed = (SshEd25519PemKey)pemKey;
        Assert.Equal(32, ed.Seed.Length);
        Assert.Equal(32, ed.PublicKey.Length);

        // The public key embedded in the private blob must match the .pub file.
        string pubFile = FixtureLoader.LoadText("ed25519_enc_key.pub");
        byte[] pubBlob = FixtureLoader.ParsePubFileBlob(pubFile);
        byte[] pubFromFile = new byte[32];
        Buffer.BlockCopy(pubBlob, 4 + 11 + 4, pubFromFile, 0, 32);
        Assert.Equal(pubFromFile, ed.PublicKey);
    }

    /// <summary>
    /// Parses an unencrypted RSA-2048 key; asserts n, e, d, p, q, coeff are all
    /// non-empty and the keytype is Rsa.
    /// </summary>
    [Fact]
    public void Parse_RsaPlain_ExtractsAllRsaParameters()
    {
        byte[] keyBytes = FixtureLoader.LoadBytes("rsa_plain_key");
        OpenSshKey openSshKey = SshPemParser.ParseOpenSshPrivateKey(keyBytes, passphrase: null);
        var pemKey = SshPemKey.Parse(openSshKey);

        Assert.Equal(SshKeyType.Rsa, pemKey.KeyType);
        var rsa = (RsaPemKey)pemKey;
        Assert.NotEmpty(rsa.Modulus);
        Assert.NotEmpty(rsa.PublicExponent);
        Assert.NotEmpty(rsa.PrivateExponent);
        Assert.NotEmpty(rsa.PrimeP);
        Assert.NotEmpty(rsa.PrimeQ);
        Assert.NotEmpty(rsa.Coefficient);

        // RSA-2048 → 256-byte modulus.
        Assert.True(rsa.Modulus.Length is >= 256 and <= 257,
            $"RSA-2048 modulus should be ~256 bytes, got {rsa.Modulus.Length}");
        // The public exponent for ssh-keygen RSA is 65537 (3 bytes: 01 00 01).
        Assert.Equal(new byte[] { 0x01, 0x00, 0x01 }, rsa.PublicExponent);
    }

    /// <summary>
    /// Parses a passphrase-encrypted RSA key with the correct passphrase; the
    /// modulus must match the encrypted key's own .pub file (the enc + plain
    /// fixtures are distinct keys, so we cross-check against the enc .pub, not
    /// the plain .pub).
    /// </summary>
    [Fact]
    public void Parse_RsaEncryptedCorrectPassphrase_PublicKeyMatchesOwnPubFile()
    {
        byte[] encBytes = FixtureLoader.LoadBytes("rsa_enc_key");
        OpenSshKey encOpenSsh = SshPemParser.ParseOpenSshPrivateKey(encBytes, passphrase: "test123");
        var encRsa = (RsaPemKey)SshPemKey.Parse(encOpenSsh);

        // Re-encode the public blob and compare to the enc key's .pub file.
        byte[] nameBytes = System.Text.Encoding.UTF8.GetBytes("ssh-rsa");
        byte[] expected = new byte[4 + nameBytes.Length + 4 + encRsa.PublicExponent.Length + 4 + encRsa.Modulus.Length];
        int offset = 0;
        WriteSshString(expected, ref offset, nameBytes);
        WriteSshString(expected, ref offset, encRsa.PublicExponent);
        WriteSshString(expected, ref offset, encRsa.Modulus);

        string pubFile = FixtureLoader.LoadText("rsa_enc_key.pub");
        byte[] pubBlob = FixtureLoader.ParsePubFileBlob(pubFile);
        Assert.Equal(pubBlob, expected);
    }

    /// <summary>
    /// PemKey.Parse on a wrong-passphrase decrypted blob fails earlier (PemParser
    /// throws KeyfileAuthFailed on check1 != check2); this test confirms PemKey
    /// never sees a bad blob.
    /// </summary>
    [Fact]
    public void Parse_WrongPassphrase_PemParserRejectsBeforePemKeyParse()
    {
        byte[] keyBytes = FixtureLoader.LoadBytes("ed25519_enc_key");
        Assert.Throws<SshException>(() =>
            SshPemParser.ParseOpenSshPrivateKey(keyBytes, passphrase: "wrongpass"));
    }

    /// <summary>
    /// The RSA public key blob from the OpenSshKey must round-trip via
    /// PemKey.Parse: re-encode the parsed n/e as a public blob
    /// [string "ssh-rsa"][string e][string n] and compare to the .pub file blob.
    /// Validates the n/e extraction order (n first in private blob, e second;
    /// but the public blob has e first, n second).
    /// </summary>
    [Fact]
    public void Parse_RsaPublicKeyBlobMatchesPubFile()
    {
        byte[] keyBytes = FixtureLoader.LoadBytes("rsa_plain_key");
        OpenSshKey openSshKey = SshPemParser.ParseOpenSshPrivateKey(keyBytes, passphrase: null);
        var rsa = (RsaPemKey)SshPemKey.Parse(openSshKey);

        // Re-encode the public blob: [4+"ssh-rsa"][4+e][4+n]
        byte[] nameBytes = System.Text.Encoding.UTF8.GetBytes("ssh-rsa");
        byte[] expected = new byte[4 + nameBytes.Length + 4 + rsa.PublicExponent.Length + 4 + rsa.Modulus.Length];
        int offset = 0;
        WriteSshString(expected, ref offset, nameBytes);
        WriteSshString(expected, ref offset, rsa.PublicExponent);
        WriteSshString(expected, ref offset, rsa.Modulus);

        // The .pub file blob is the canonical reference.
        string pubFile = FixtureLoader.LoadText("rsa_plain_key.pub");
        byte[] pubBlob = FixtureLoader.ParsePubFileBlob(pubFile);
        Assert.Equal(pubBlob, expected);
    }

    private static void WriteSshString(byte[] buf, ref int offset, byte[] bytes)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(buf.AsSpan(offset, 4), (uint)bytes.Length);
        offset += 4;
        Buffer.BlockCopy(bytes, 0, buf, offset, bytes.Length);
        offset += bytes.Length;
    }
}
